### ISSUE TITLE
Required OpenCL support for clFFT

### ISSUE THREAD

**Issue by MichalKuderjavy** [clMathLibraries/clFFT#174]
Hello,

there is a note in readme file that says clFFT requires OpenCL 1.2. I have been able to run clFFT on GPUs that support only 1.1 or 1.0. Can I rely on that, or will it fail in some situations? Or is it that there are some library functions that specifically require OpenCL 1.2 support, while others do not?

With Regards,
Michal

**Comment by pavanky** [comment]
@MichalKuderjavy What GPUs have you run on and what version of clFFT?

**Comment by MichalKuderjavy** [comment]
We are using clFFT 2.12.0. We have tried NVIDIA GTS 450 (OpenCL 1.1), NVIDIA GTS 250 (probably OpenCL 1.0, but we do not have this card available right now), NVIDIA 9400 GT (OpenCL 1.0) and it seems to be working.

**Comment by bragadeesh** [comment]
The opencl 1.2 requirement is stated from a testing/qa perspective. We have only tested/validated on opencl 1.2 supported platforms on AMD hardware. It is quite possible that it works fine with 1.1 & 1.0 but we cannot state that because we have not tested that. Also, Opencl 1.2 is backward compatible with 1.1 & 1.0. The only way to make sure is to test your usage scenarios. I am closing this issue.
