### ISSUE TITLE
clFFT work group size problem on Radeon 4600 GPUs

### ISSUE THREAD

**Issue by PhilSee** [clMathLibraries/clFFT#67]
Hi,

we're testing clFFT 2.2 on our Radeon HD 4670 card and are experiencing some problems: For the generated FFT kernel our OpenCL runtime (Catalyst 13.9, APP SDK 2.8.1) reports a maximum work group size of 32. However, as far as I could see in the sources, a minimum work group size of 64 or higher is coded by the kernel generators. 

Unfortunately this totally prevents clFFT from executing on our Radeon 4670, the client test program stops with an insufficient resources error.

So, without knowing much about the internals of the FFT kernels: Would it be possible to set down the required work group size to 32 in the kernel generators? In our application we would need two-dimensional FFTs with block sizes ranging from 64x64 to 256x256.

We are aware that the Radeon 4600 family nowadays is a legacy core with limited resources, stemming from the early days of OpenCL support on Radeon GPUs. However, we eventually would use the FFT on a long-running embedded E4690 platform and it would be really great to have the FFT capability on this core.

Thanks,
Philipp

**Comment by kknox** [comment]
Could you post the clinfo output for this device?  Also, which OS?

**Comment by PhilSee** [comment]
We're using Win 7 Professional. I'm currently not at the hardware but I'll try to get you the clinfo output tomorrow. But as far as I can remember for the 4670 device

...
  Max work items dimensions:			 3
    Max work items[0]:				 128
    Max work items[1]:				 128
    Max work items[2]:				 128
  Max work group size:				 128
...

was reported. However, clGetKernelWorkGroupInfo(CL_KERNEL_WORK_GROUP_SIZE) reports 32 for slightly more advanced kernels as the FFT kernels seem to be.

**Comment by bragadeesh** [comment]
As you are saying that generation is no longer supported. Unfortunately, I cannot devote too much time on this for that reason. Since the code is open-source, you could try modifying the code yourself and see if you can make it work for your platform. I can give you some pointers on how to change the code:

Using the develop branch of clFFT with the latest commit id of: 18b7c433485853f90e37f8074129da2ce46225da

the 2D fft by default has to use not just fft kernels but also the transpose kernels. First you have to disable the transpose kernels by un-commenting the break statement at line number 1508 in plan.cpp. This should make all 2D computations to not use transposes. Then, you have to modify the tables in generator.stockham.cpp at lines 217-224, 255-258, 274-277. You just have to change the numbers in the second column, which is the work group size. They all can be set to 32. This should take care of power-of-2 size transforms (I am assuming you are only doing this). 

You can try this and see if it will work. You may run into issues, I cannot give any guarantee, you have to run tests to make sure etc.

**Comment by PhilSee** [comment]
Hi, 

thanks a lot for the information and your hints. I set up a clFFT build environment based on the latest develop branch commit and made the changes you suggested. Unfortunately that didn't do the trick entirely, clfftBakePlan still doesn't seem to be too happy with the work group sizes.

I will do some further experimentation on this issue. Meanwhile the clinfo output and clfft-client's cli output (new build with work group sizes already set to 32) are available via a separate gist repo:

https://gist.github.com/PhilSee/ed046f0dd3e73bfa39f6

**Comment by bragadeesh** [comment]
Try troubleshooting going from the basics.
I am not sure if we supported the '-d' flag for the client program. If that works, it will dump the OpenCL kernel on to the disk and you can inspect what work group size it uses. You can start with a small size such as 4 and 1D and see if that works.
./Client -x 4 -d

**Comment by PhilSee** [comment]
Thanks for your response. Meanwhile we actually managed to get clFFT running for our purposes on the Radeon HD 4670 platform. The secret was the initialization of limit_WorkGroupSize (set to MAX_WORK_GROUP_SIZE = 128 on Radeon 4600 devices) which caused DetermineSizes(...) to kick in before kernel generation, effectively overriding the work group size and num transform settings from the tables.

So as said for our purposes clFFT is actually usable now and most testcases are passing successfully in the regression test runs. However, in some constellations (somewhat random, large FFT sizes, more FFT dimensions) some accuracy test cases fail due to numerical precision issues. But given our application I think we can live with that for now.

**Comment by bragadeesh** [comment]
Thanks for providing us with an update; glad to know that it is working with your environment.
